<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit des apprenants</title>

    <style>
        body {
            display: flex;
            flex-direction: column;
            flex-wrap: wrap;
            align-items: center;
        }

        label {

            display: inline-block;
            width: 200px;
            font-weight: bold;
            margin-bottom: 1rem;
        }

        .submit {
            display: inline-block;
            margin: auto;
        }

        div input {

            width: 450px;
        }
    </style>
</head>

<body>
    <h1>Modifier l'apprenant :</h1>


    <form action="" method="POST">
        <input type="hidden" name="id" value="<?= $apprenant['id'] ?>">

        <div>
            <label for="">Prénom</label>
            <input type="text" name="firstname" value="<?= $apprenant['firstname'] ?>">
        </div>
        <div>
            <label for="">Nom :</label>
            <input type="text" name="lastname" value="<?= $apprenant['lastname'] ?>">
        </div>
        <div>
            <label for="">Date de naissance :</label>
            <input type="text" name="birthyear" value="<?= $apprenant['birthyear'] ?>">
        </div>
        <div>
            <label for="">Ville de naissance :</label>
            <input type="text" name="birthcity" value="<?= $apprenant['birthcity'] ?>">
        </div>
        <div>
            <label for="">Film préféré :</label>
            <input type="text" name="lovedmovie" value="<?= $apprenant['lovedmovie'] ?>">
        </div>
        <div>
            <label for="">Chansson :</label>
            <input type="text" name="lovedsong" value="<?= $apprenant['lovedsong'] ?>">
        </div>
        <div>
            <label for="">Citation :</label>
            <input type="text" name="lovedquote" value="<?= $apprenant['lovedquote'] ?>">
        </div>



        <input type="submit" value="Enregistrer">
    </form>
</body>

</html>