<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liste des apprenants</title>

    <style>
        * {
            margin: 0;
            padding: 0;
        }

        table {
            width: 100%;
            text-align: center;
            border: 1px solid black;

            margin: 10px 0px;
        }

        table {
            border-collapse: collapse;
        }

        td {
            padding: 10px;
            border-top: 1px solid black;
        }

        article {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        div {
            text-align: center;
            border: 2px solid black;
            width: 20%;
            margin: 50px;
            padding: 20px;
        }
    </style>
</head>

<body>
    <h1>Liste des apprenants Développeurs Surya</h1>


    <!-- foreach table  -->


    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Date de naissance</th>
                <th>Ville de naissance</th>
                <th>Actions</th>

            </tr>
        </thead>

        <tbody>
            <?php foreach ($apprenants as $apprenant) : ?>
                <tr>
                    <td><?= $apprenant['id'] ?></td>
                    <td><?= $apprenant['firstname'] ?></td>
                    <td><?= $apprenant['lastname'] ?></td>
                    <td><?= $apprenant['birthyear'] ?></td>
                    <td><?= $apprenant['birthcity'] ?></td>
                    <td>
                        <a href="detail_apprenant.php?id=<?= $apprenant['id'] ?>">Voir</a>
                        <a href="edit_apprenant.php?id=<?= $apprenant['id'] ?>">Modifier</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>



    <hr>

    <section>


        <article>
            <?php foreach ($apprenants as $apprenant) : ?>
                <div>
                    <h2><?= $apprenant['firstname'] ?> <?= $apprenant['lastname'] ?></h2>

                    <p>Date de naissance : <?= $apprenant['birthyear'] ?></p>
                    <p>Ville de naissance : <?= $apprenant['birthcity'] ?></p>
                    <a href="detail_apprenant.php?id=<?= $apprenant['id'] ?>">Voir</a>
                    <a href="edit_apprenant.php?id=<?= $apprenant['id'] ?>">Modifier</a>
                </div>
            <?php endforeach; ?>
        </article>
    </section>
</body>

</html>