<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Démonstration d'un formulaire de connexion (page de profil)</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <style>
        .img-force-fluid{
            width: 100%; /* PAS BIEN ! IL NE FAUT JAMAIS FAIRE CELA */
        }
    </style>
</head>
<body>
    
    <header class="mb-5 p-5 bg-primary text-white rounded">
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <h1>Bienvenue agent <?=$lastname?> (<a href="readme.php" target="_blank" class="link-warning">lire l'énoncé</a>)</h1>
                    <hr>
                    <p>Voici votre profil Mission Impossible.</p>
                </div>
                <div class="col-4 text-end">
                    <a href="logout.php" class="btn btn-outline-light" ><i class="fa-solid fa-right-from-bracket"></i> Déconnexion</a>
                </div>
            </div>
        </div>
    </header>
    
    <section id="profil">
        <div class="container">
            <div class="row">
                <div class="col-4 offset-2">
                    <img class="img-force-fluid" src="images/actors/<?=$actorPhoto?>" alt="">
                </div>
                <div class="col-4">
                    <h2 class="display-4">Agent <?=$firstname?> <?=$lastname?></h2>
                    <h3><?=$email?></h3>
                    <p><strong>Incarné par </strong><?=$actorFirstname?> <?=$actorLastname?></p>
                    <p><strong>Né(e) le </strong><?=$actorBirthDate?></p>
                    <p><?=$description?></p>
                </div>
            </div>
        </div>
    </section> 

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/ffe3aa3664.js" crossorigin="anonymous"></script>
</body>
</html>