<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link rel="stylesheet" href="css/cocktails.css">
</head>

<body>

    <?php include 'vues/nav.phtml'; ?>

    <!-- DÉBUT DU HEADER -->
    <?php include 'vues/header.phtml'; ?>
    <!-- FIN DU HEADER -->


    <!-- DÉBUT DU MAIN -->
    <main>
        <section class="d-flex justify-content-center">
            <div class="col-7 card mb-3 mt-5">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="images/cocktails/<?= $cocktailById['image'] ?>" class="img-fluid rounded-start" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title fs-2 fw-bold"><?= $cocktailById['name'] ?></h5>
                            <p class="card-text"> <?= $cocktailById['description'] ?></p>
                            <div class="col-4">
                                <p class="card-text"><small class="text-muted">Année : <?= $cocktailById['year'] ?></small></p>
                                <p class="card-text"><small class="text-muted">Prix : <?= $cocktailById['price'] ?>€</small></p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-2 mt-5 a">

                <ul class="list-group">
                    <li class="list-group-item list-group-item-action border-warning bg-warning active" aria-current="true"> Ingrédients</li>
                    <?php foreach ($ingredients as $ingredient) : ?>
                        <li class="list-group-item py-1"><?= $ingredient['name'] ?></li>
                    <?php endforeach; ?>
                </ul>

            </div>


        </section>
    </main>
    <!-- FIN DU MAIN -->

    <?php include 'vues/footer.phtml'; ?>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
</body>

</html>