<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Classic Models - Liste des commandes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
    <h1>Liste des commandes (<?=$nbOrders?>)</h1>
    
    <form action="" method="POST">
       
        <input type="text"  name="customerName" id="customerName" placeholder="Client" >
        <input type="submit" value="Rechercher" class="btn btn-primary">
    </form>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Numéro</th>
                <th>Nom Client</th>
                <th>Date de commande</th>
                <th>Statut</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($orders as $order) : ?>
            <tr>
                <td><a href="invoice.php?orderNumber=<?=$order['orderNumber']?>"><?=$order['orderNumber']?></a></td>
                <td><?=$order['customerName']?></td>
                <td><?=$order['orderDate']?></td>
                <td><?=$order['status']?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
</body>
</html>