<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Classic Models - Liste des commandes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col">

                <h1>Détail de la commande #<?=$orderNumber?></h1>
                <a href="index.php" class="btn btn-primary">&lt; Retour</a>
                <p>
                    <h2>Client #<?=$customerNumber?></h2>
                </p>                
                <p>
                    <strong><?=$customerDetails['customerName'];?></strong>
                </p>
                <p>
                    <strong><?=$customerDetails['contactLastName'];?> <?=$customerDetails['contactFirstName'];?></strong>
                </p>
                <p>
                    <strong>
                        <?=$customerDetails['addressLine1'];?><br>
                        <?=$customerDetails['addressLine2'];?>
                    </strong>
                </p>
                <p>
                    <strong><?=$customerDetails['postalCode'];?> <?=$customerDetails['city'];?></strong>
                </p>
                <p>
                    <strong><?=$customerDetails['state'];?> <?=$customerDetails['country'];?></strong>
                </p>

                <table class="table table-striped table-hover">
                    <thead>
                        <th>Produit</th>
                        <th class="text-center">Quantité</th>
                        <th class="text-center">Prix Unitaire</th>
                        <th class="text-center">Total</th>
                    </thead>
                    <tbody>
                        <?php foreach ($orderDetails as $orderDetail) : ?>
                            <tr>
                                <td><?=$orderDetail['productName']?></td>
                                <td class="text-center"><?=$orderDetail['quantityOrdered']?></td>
                                <td class="text-center"><?=$orderDetail['priceEach']?>$</td>
                                <td class="text-center"><?=$orderDetail['total']?>$</td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3" class="text-end"> <strong> Total HT</strong></td>
                            <td class="text-center"><?=$HT?>$</td>
                        </tr>
                        <tr>
                            <td colspan="3" class="text-end"> <strong> TVA</strong></td>
                            <td class="text-center"><?=$TVA?>$</td>
                        </tr>
                        <tr>
                            <td colspan="3" class="text-end"> <strong> Total TTC</strong></td>
                            <td class="text-center"><?=$TTC?>$</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
</body>

</html>