<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Mister Cocktail</title>
    <!-- Charger CSS de bootstrap, police Montserrat sur Google Fonts et le CSS de l'application -->
</head>
<body class="container-fluid">
    <nav>
        <a href="index.php">Accueil</a>
        <h1>Mister Cocktail</h1>
    </nav>

    <h2>Détails d'un cocktail</h2>
    
</body>
</html>