<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <link href="www/css/cocktails.css" rel="stylesheet">>
<title>Mister Cocktail</title>
    <!-- Charger CSS de bootstrap, police Montserrat sur Google Fonts et le CSS de l'application -->
</head>
<body class="container-fluid">
    <nav>
        <a href="index.php">Accueil</a>
        <h1>Mister Cocktail</h1>
    </nav>

    <main>
        <!-- Listing de tous les cocktails -->
        <main>
        <?php foreach($cocktails as $cocktail){ ?>

            <article class="card cocktail">
                <a href="details_cocktail.php?id=votre_id">
                    <img class="card-img-top" src="www/images/cocktails/<?= $cocktail['image'] ?> " alt="image" width="30px">
                </a>
                <div class="card-body">
                    <h4 class="card-title"> <?= $cocktail['name'] ?></h4>
                    <p class="card-text"><?= $cocktail['description'] ?></p>
                </div>
            </article>
       <?php } ?>
       
    </main>
</body>
</html> 