<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Démonstration d'un formulaire de connexion</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
</head>
<body>
    
    <header class="mb-5 p-5 bg-primary text-white rounded">
        <div class="container">
        <h1>Démonstration d'un formulaire de connexion (<a href="readme.php" target="_blank" class="link-warning">lire l'énoncé</a>)</h1>
        <hr>
        <p>Utilisez le formulaire ci-dessous pour vous connecter.</p>
        </div>
    </header>

    <section id="connection-form">
        <div class="container">
            <div class="row">
                <div class="col-4 offset-4">
                    <?php if(isset($message) && $message != '') : ?>
                            <div class="alert alert-danger" role="alert">
                                <?=$message?>
                            </div>
                            <?php endif; ?>   
                    </div>
                <div class="col-4 offset-4">
                    <div class="card p-2 bg-light">
                        <h3 class="my-3 text-center">Identification</h3> 

                        <form action="index.php" method="post">
                            <div class="row mb-3">
                                <label for="email" class="col-4 col-form-label text-end">Email</label>
                                <div class="col-8">
                                    <input type="email" class="form-control" name="email" id="email" value="<?=$email?>">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="password" class="col-4 col-form-label text-end">Mot de passe</label>
                                <div class="col-8">
                                    <input type="password" class="form-control"  name="password" id="password" value="<?=$password?>">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <div class="col text-end">
                                    <input type="submit" class="btn btn-primary" value="Me connecter">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
   
            </div>
        </div>
    </section> 

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/ffe3aa3664.js" crossorigin="anonymous"></script>
</body>
</html>