<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/cocktails.css">
    <!-- Charger CSS de bootstrap, police Montserrat sur Google Fonts et le CSS de l'application -->
</head>
<body class="container-fluid">
    <nav>
    <?php include "assets/templates/navbar.phtml"?>
    </nav>

    <h2>Ajout d'un nouveau cocktail</h2>
    <form action="add_cocktails.php" method="POST" enctype="multipart/form-data">
        <div class="form-group col-4">
            <label for="idFamille">Famille :</label>
            <select class="form-control" id="idFamille" name="idFamille">
                <?php foreach($famille_cocktails as $key){?>
                    <option value="<?= $key['id'] ?>"> <?= $key['name'] ?> </option>
                <?php } ?>
            </select>
        </div>
        <div class="form-group col-8">
            <label for="nom">Nom :</label>
            <input type="text" class="form-control" id="nom" name="name" maxlength="30">
        </div>
        
        <div class="form-group col-12">
            <label for="description">Description :</label>
            <textarea class="form-control" id="description" name="description"></textarea>
        </div>
        <div class="form-group col-3">
            <label for="anneeConception">Année conception :</label>
            <input type="number" class="form-control" id="anneeConception" name="anneeConception" placeholder="1900">
        </div>
        <div class="form-group col-3">
            <label for="nom">Prix moyen :</label>
            <input type="text" class="form-control" id="prixMoyen" name="prixMoyen">
        </div>
        <br>
        <div class="mb-3">
        <label for="formFile" class="form-label">Importer images :</label>
        <input class="form-control" type="file" id="formFile" name="formFile">
        </div>
        <br>
        <div class="form-group col-12">
            <button type="submit" class="btn btn-primary">Enregistrer</button>
        </div>

    </form>