<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com/%22%3E">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/cocktails.css">
    <!-- Charger CSS de bootstrap, police Montserrat sur Google Fonts et le CSS de l'application -->
</head>
<body class="container-fluid">
    <nav>
    <?php include "assets/templates/navbar.phtml"?>
    </nav>

    <h2>Détails d'un cocktail</h2>
    <ul>
        <li> Nom : <?= $cocktails['name']?></li>
        <li> Famille : <?= $cocktails['type_alcool']?></li>
        <li> Description : <?= $cocktails['description']?></li>
        <li> Ingrédients :  </li>
        <ul>
        <?php foreach($ingredient as $key){ ?>
        <li> <?= $key['name'] ?> </li>
        <?php } ?>
        </ul>
        <li> Année de conception :<?= $cocktails['year']?></li>
        <li> Prix moyen :<?= $cocktails['price']?></li>
    </ul>
</body>
</html>
